changelog:
  format: "- $title in $hash"
  categories:
    - title: "💎 Features"
      labels:
        - "feature"
        - "enhancement"
      prefixes:
        - "feat"
        - "feat:"
    - title: "🩺 Fixes"
      labels:
        - "fix"
        - "bug"
      prefixes:
        - "fix"
        - "fix:"
    - title: "🏎️ Performance"
      labels:
        - "perf"
      prefixes:
        - "perf"
        - "perf:"
    - title: "🧪 Refactor"
      labels:
        - "refactor"
      prefixes:
        - "refactor"
        - "refactor:"
    - title: "🔧 Maintenance"
      labels:
        - "chore"
        - "maintenance"
      prefixes:
        - "chore"
        - "chore:"
    - title: "🚀 Other Changes"
      labels:
        - "*"
      prefixes:
        - "*"

  exclude:
    labels:
      - "ignore-for-release"
    authors:
      - "dependabot[bot]"
      - "github-actions[bot]"

contributors:
  enabled: false
