changelog:
  format: "- $title in $hash"
  categories:
    - title: "💎 Features"
      labels:
        - "feature"
        - "enhancement"
      prefix: "feat"
    - title: "🩺 Fixes"
      labels:
        - "fix"
        - "bug"
      prefix: "fix"
    - title: "🏎️ Performance"
      labels:
        - "perf"
      prefix: "perf"
    - title: "🧪 Refactor"
      labels:
        - "refactor"
      prefix: "refactor"
    - title: "🔧 Chore"
      labels:
        - "chore"
      prefix: "chore"

  exclude:
    labels:
      - "ignore-for-release"
    authors:
      - "dependabot[bot]"
      - "github-actions[bot]"

contributors:
  enabled: false
