// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://127.0.0.1:8000' | (string & {});
};

/**
 * Body_login_api_auth_login_post
 */
export type BodyLoginApiAuthLoginPost = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * CarCreate
 */
export type CarCreate = {
    /**
     * Brand
     */
    brand: string;
    /**
     * Model
     */
    model: string;
    /**
     * Year
     */
    year: number;
    /**
     * Initial Odometer Km
     */
    initial_odometer_km: number;
};

/**
 * CarRead
 */
export type CarRead = {
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Brand
     */
    brand: string;
    /**
     * Model
     */
    model: string;
    /**
     * Year
     */
    year: number;
    /**
     * Initial Odometer Km
     */
    initial_odometer_km: number;
    /**
     * Current Odometer Km
     */
    current_odometer_km: number;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * CarUpdate
 */
export type CarUpdate = {
    /**
     * Brand
     */
    brand?: string | null;
    /**
     * Model
     */
    model?: string | null;
    /**
     * Year
     */
    year?: number | null;
};

/**
 * ChangePasswordRequest
 */
export type ChangePasswordRequest = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * MileageLogCreate
 */
export type MileageLogCreate = {
    /**
     * Car Id
     */
    car_id: string;
    /**
     * Odometer Km
     */
    odometer_km: number;
};

/**
 * MileageLogRead
 */
export type MileageLogRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Car Id
     */
    car_id: string;
    /**
     * Odometer Km
     */
    odometer_km: number;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * ReminderCreate
 */
export type ReminderCreate = {
    /**
     * Service Item Id
     */
    service_item_id: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Interval Km
     */
    interval_km?: number | null;
    /**
     * Interval Days
     */
    interval_days?: number | null;
    /**
     * Notify Before Km
     */
    notify_before_km?: number | null;
    /**
     * Notify Before Days
     */
    notify_before_days?: number | null;
    /**
     * Note
     */
    note?: string | null;
};

/**
 * ReminderRead
 */
export type ReminderRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Service Item Id
     */
    service_item_id: string;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Interval Km
     */
    interval_km: number | null;
    /**
     * Interval Days
     */
    interval_days: number | null;
    /**
     * Notify Before Km
     */
    notify_before_km: number | null;
    /**
     * Notify Before Days
     */
    notify_before_days: number | null;
    /**
     * Last Notified At
     */
    last_notified_at?: string | null;
    /**
     * Note
     */
    note: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * ReminderUpdate
 */
export type ReminderUpdate = {
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Interval Km
     */
    interval_km?: number | null;
    /**
     * Interval Days
     */
    interval_days?: number | null;
    /**
     * Notify Before Km
     */
    notify_before_km?: number | null;
    /**
     * Notify Before Days
     */
    notify_before_days?: number | null;
    /**
     * Note
     */
    note?: string | null;
};

/**
 * ServiceItemCreate
 */
export type ServiceItemCreate = {
    /**
     * Car Id
     */
    car_id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Last Service At
     */
    last_service_at: string;
    /**
     * Last Service Odometer Km
     */
    last_service_odometer_km: number;
};

/**
 * ServiceItemMarkServiced
 */
export type ServiceItemMarkServiced = {
    /**
     * Serviced At
     */
    serviced_at: string;
    /**
     * Odometer Km
     */
    odometer_km: number;
};

/**
 * ServiceItemRead
 */
export type ServiceItemRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Car Id
     */
    car_id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Last Service At
     */
    last_service_at: string;
    /**
     * Last Service Odometer Km
     */
    last_service_odometer_km: number;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * ServiceItemStatus
 */
export type ServiceItemStatus = 'ok' | 'soon' | 'due';

/**
 * ServiceItemSummary
 */
export type ServiceItemSummary = {
    /**
     * Id
     */
    id: string;
    /**
     * Car Id
     */
    car_id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Last Service At
     */
    last_service_at: string;
    /**
     * Last Service Odometer Km
     */
    last_service_odometer_km: number;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    status?: ServiceItemStatus;
    /**
     * Km Until Due
     */
    km_until_due?: number | null;
    /**
     * Days Until Due
     */
    days_until_due?: number | null;
};

/**
 * ServiceItemUpdate
 */
export type ServiceItemUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Last Service At
     */
    last_service_at?: string | null;
    /**
     * Last Service Odometer Km
     */
    last_service_odometer_km?: number | null;
};

/**
 * TelegramAuthRequest
 */
export type TelegramAuthRequest = {
    /**
     * Init Data Raw
     */
    init_data_raw: string;
};

/**
 * TelegramLinkTokenResponse
 */
export type TelegramLinkTokenResponse = {
    /**
     * Token
     */
    token: string;
    /**
     * Bot Username
     */
    bot_username?: string | null;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Username
     */
    username: string;
    /**
     * Name
     */
    name: string;
    /**
     * Password
     */
    password: string;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * UserRead
 */
export type UserRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Telegram Id
     */
    telegram_id?: number | null;
    /**
     * Username
     */
    username: string;
    /**
     * Name
     */
    name: string;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * UserSettingsRead
 */
export type UserSettingsRead = {
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Service Reminder Time
     */
    service_reminder_time: string;
    /**
     * Mileage Reminder Time
     */
    mileage_reminder_time: string;
    /**
     * Mileage Prompt Interval Days
     */
    mileage_prompt_interval_days?: number | null;
    /**
     * Timezone
     */
    timezone: string;
    /**
     * Notify Via Telegram
     */
    notify_via_telegram: boolean;
    /**
     * Notify Via Email
     */
    notify_via_email: boolean;
    /**
     * Language
     */
    language: 'ru' | 'en';
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * UserSettingsUpdate
 */
export type UserSettingsUpdate = {
    /**
     * Service Reminder Time
     */
    service_reminder_time?: string | null;
    /**
     * Mileage Reminder Time
     */
    mileage_reminder_time?: string | null;
    /**
     * Mileage Prompt Interval Days
     */
    mileage_prompt_interval_days?: number | null;
    /**
     * Timezone
     */
    timezone?: string | null;
    /**
     * Notify Via Telegram
     */
    notify_via_telegram?: boolean | null;
    /**
     * Notify Via Email
     */
    notify_via_email?: boolean | null;
    /**
     * Language
     */
    language?: 'ru' | 'en' | null;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Username
     */
    username?: string | null;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type LoginApiAuthLoginPostData = {
    body: BodyLoginApiAuthLoginPost;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type LoginApiAuthLoginPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginApiAuthLoginPostError = LoginApiAuthLoginPostErrors[keyof LoginApiAuthLoginPostErrors];

export type LoginApiAuthLoginPostResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type LoginApiAuthLoginPostResponse = LoginApiAuthLoginPostResponses[keyof LoginApiAuthLoginPostResponses];

export type LogoutApiAuthLogoutPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/logout';
};

export type LogoutApiAuthLogoutPostResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type LogoutApiAuthLogoutPostResponse = LogoutApiAuthLogoutPostResponses[keyof LogoutApiAuthLogoutPostResponses];

export type GetMeApiAuthMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/me';
};

export type GetMeApiAuthMeGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMeApiAuthMeGetError = GetMeApiAuthMeGetErrors[keyof GetMeApiAuthMeGetErrors];

export type GetMeApiAuthMeGetResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type GetMeApiAuthMeGetResponse = GetMeApiAuthMeGetResponses[keyof GetMeApiAuthMeGetResponses];

export type ChangePasswordApiAuthChangePasswordPostData = {
    body: ChangePasswordRequest;
    path?: never;
    query?: never;
    url: '/api/auth/change-password';
};

export type ChangePasswordApiAuthChangePasswordPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChangePasswordApiAuthChangePasswordPostError = ChangePasswordApiAuthChangePasswordPostErrors[keyof ChangePasswordApiAuthChangePasswordPostErrors];

export type ChangePasswordApiAuthChangePasswordPostResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type ChangePasswordApiAuthChangePasswordPostResponse = ChangePasswordApiAuthChangePasswordPostResponses[keyof ChangePasswordApiAuthChangePasswordPostResponses];

export type RegisterUserApiUsersPostData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/users';
};

export type RegisterUserApiUsersPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterUserApiUsersPostError = RegisterUserApiUsersPostErrors[keyof RegisterUserApiUsersPostErrors];

export type RegisterUserApiUsersPostResponses = {
    /**
     * Successful Response
     */
    201: UserRead;
};

export type RegisterUserApiUsersPostResponse = RegisterUserApiUsersPostResponses[keyof RegisterUserApiUsersPostResponses];

export type GetUserByUsernameApiUsersUusernameGetData = {
    body?: never;
    path: {
        /**
         * Username
         */
        username: string;
    };
    query?: never;
    url: '/api/users/u/{username}';
};

export type GetUserByUsernameApiUsersUusernameGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUserByUsernameApiUsersUusernameGetError = GetUserByUsernameApiUsersUusernameGetErrors[keyof GetUserByUsernameApiUsersUusernameGetErrors];

export type GetUserByUsernameApiUsersUusernameGetResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type GetUserByUsernameApiUsersUusernameGetResponse = GetUserByUsernameApiUsersUusernameGetResponses[keyof GetUserByUsernameApiUsersUusernameGetResponses];

export type DeleteUserApiUsersUserIdDeleteData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/users/{user_id}';
};

export type DeleteUserApiUsersUserIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteUserApiUsersUserIdDeleteError = DeleteUserApiUsersUserIdDeleteErrors[keyof DeleteUserApiUsersUserIdDeleteErrors];

export type DeleteUserApiUsersUserIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteUserApiUsersUserIdDeleteResponse = DeleteUserApiUsersUserIdDeleteResponses[keyof DeleteUserApiUsersUserIdDeleteResponses];

export type GetUserApiUsersUserIdGetData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/users/{user_id}';
};

export type GetUserApiUsersUserIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUserApiUsersUserIdGetError = GetUserApiUsersUserIdGetErrors[keyof GetUserApiUsersUserIdGetErrors];

export type GetUserApiUsersUserIdGetResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type GetUserApiUsersUserIdGetResponse = GetUserApiUsersUserIdGetResponses[keyof GetUserApiUsersUserIdGetResponses];

export type UpdateUserApiUsersUserIdPatchData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/users/{user_id}';
};

export type UpdateUserApiUsersUserIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUserApiUsersUserIdPatchError = UpdateUserApiUsersUserIdPatchErrors[keyof UpdateUserApiUsersUserIdPatchErrors];

export type UpdateUserApiUsersUserIdPatchResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type UpdateUserApiUsersUserIdPatchResponse = UpdateUserApiUsersUserIdPatchResponses[keyof UpdateUserApiUsersUserIdPatchResponses];

export type GetMySettingsApiUsersMeSettingsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users/me/settings';
};

export type GetMySettingsApiUsersMeSettingsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMySettingsApiUsersMeSettingsGetError = GetMySettingsApiUsersMeSettingsGetErrors[keyof GetMySettingsApiUsersMeSettingsGetErrors];

export type GetMySettingsApiUsersMeSettingsGetResponses = {
    /**
     * Successful Response
     */
    200: UserSettingsRead;
};

export type GetMySettingsApiUsersMeSettingsGetResponse = GetMySettingsApiUsersMeSettingsGetResponses[keyof GetMySettingsApiUsersMeSettingsGetResponses];

export type UpdateMySettingsApiUsersMeSettingsPatchData = {
    body: UserSettingsUpdate;
    path?: never;
    query?: never;
    url: '/api/users/me/settings';
};

export type UpdateMySettingsApiUsersMeSettingsPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateMySettingsApiUsersMeSettingsPatchError = UpdateMySettingsApiUsersMeSettingsPatchErrors[keyof UpdateMySettingsApiUsersMeSettingsPatchErrors];

export type UpdateMySettingsApiUsersMeSettingsPatchResponses = {
    /**
     * Successful Response
     */
    200: UserSettingsRead;
};

export type UpdateMySettingsApiUsersMeSettingsPatchResponse = UpdateMySettingsApiUsersMeSettingsPatchResponses[keyof UpdateMySettingsApiUsersMeSettingsPatchResponses];

export type ListUserCarsApiCarsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/cars';
};

export type ListUserCarsApiCarsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListUserCarsApiCarsGetError = ListUserCarsApiCarsGetErrors[keyof ListUserCarsApiCarsGetErrors];

export type ListUserCarsApiCarsGetResponses = {
    /**
     * Response List User Cars Api Cars Get
     *
     * Successful Response
     */
    200: Array<CarRead>;
};

export type ListUserCarsApiCarsGetResponse = ListUserCarsApiCarsGetResponses[keyof ListUserCarsApiCarsGetResponses];

export type AddCarApiCarsPostData = {
    body: CarCreate;
    path?: never;
    query?: never;
    url: '/api/cars';
};

export type AddCarApiCarsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddCarApiCarsPostError = AddCarApiCarsPostErrors[keyof AddCarApiCarsPostErrors];

export type AddCarApiCarsPostResponses = {
    /**
     * Successful Response
     */
    201: CarRead;
};

export type AddCarApiCarsPostResponse = AddCarApiCarsPostResponses[keyof AddCarApiCarsPostResponses];

export type DeleteCarApiCarsCarIdDeleteData = {
    body?: never;
    path: {
        /**
         * Car Id
         */
        car_id: string;
    };
    query?: never;
    url: '/api/cars/{car_id}';
};

export type DeleteCarApiCarsCarIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteCarApiCarsCarIdDeleteError = DeleteCarApiCarsCarIdDeleteErrors[keyof DeleteCarApiCarsCarIdDeleteErrors];

export type DeleteCarApiCarsCarIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteCarApiCarsCarIdDeleteResponse = DeleteCarApiCarsCarIdDeleteResponses[keyof DeleteCarApiCarsCarIdDeleteResponses];

export type GetCarApiCarsCarIdGetData = {
    body?: never;
    path: {
        /**
         * Car Id
         */
        car_id: string;
    };
    query?: never;
    url: '/api/cars/{car_id}';
};

export type GetCarApiCarsCarIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCarApiCarsCarIdGetError = GetCarApiCarsCarIdGetErrors[keyof GetCarApiCarsCarIdGetErrors];

export type GetCarApiCarsCarIdGetResponses = {
    /**
     * Successful Response
     */
    200: CarRead;
};

export type GetCarApiCarsCarIdGetResponse = GetCarApiCarsCarIdGetResponses[keyof GetCarApiCarsCarIdGetResponses];

export type UpdateCarApiCarsCarIdPatchData = {
    body: CarUpdate;
    path: {
        /**
         * Car Id
         */
        car_id: string;
    };
    query?: never;
    url: '/api/cars/{car_id}';
};

export type UpdateCarApiCarsCarIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateCarApiCarsCarIdPatchError = UpdateCarApiCarsCarIdPatchErrors[keyof UpdateCarApiCarsCarIdPatchErrors];

export type UpdateCarApiCarsCarIdPatchResponses = {
    /**
     * Successful Response
     */
    200: CarRead;
};

export type UpdateCarApiCarsCarIdPatchResponse = UpdateCarApiCarsCarIdPatchResponses[keyof UpdateCarApiCarsCarIdPatchResponses];

export type ListByCarApiMileageLogsGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Car Id
         */
        car_id: string;
    };
    url: '/api/mileage-logs';
};

export type ListByCarApiMileageLogsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListByCarApiMileageLogsGetError = ListByCarApiMileageLogsGetErrors[keyof ListByCarApiMileageLogsGetErrors];

export type ListByCarApiMileageLogsGetResponses = {
    /**
     * Response List By Car Api Mileage Logs Get
     *
     * Successful Response
     */
    200: Array<MileageLogRead>;
};

export type ListByCarApiMileageLogsGetResponse = ListByCarApiMileageLogsGetResponses[keyof ListByCarApiMileageLogsGetResponses];

export type AddMileageLogApiMileageLogsPostData = {
    body: MileageLogCreate;
    path?: never;
    query?: never;
    url: '/api/mileage-logs';
};

export type AddMileageLogApiMileageLogsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddMileageLogApiMileageLogsPostError = AddMileageLogApiMileageLogsPostErrors[keyof AddMileageLogApiMileageLogsPostErrors];

export type AddMileageLogApiMileageLogsPostResponses = {
    /**
     * Successful Response
     */
    201: MileageLogRead;
};

export type AddMileageLogApiMileageLogsPostResponse = AddMileageLogApiMileageLogsPostResponses[keyof AddMileageLogApiMileageLogsPostResponses];

export type DeleteMileageLogApiMileageLogsMileageLogIdDeleteData = {
    body?: never;
    path: {
        /**
         * Mileage Log Id
         */
        mileage_log_id: string;
    };
    query?: never;
    url: '/api/mileage-logs/{mileage_log_id}';
};

export type DeleteMileageLogApiMileageLogsMileageLogIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteMileageLogApiMileageLogsMileageLogIdDeleteError = DeleteMileageLogApiMileageLogsMileageLogIdDeleteErrors[keyof DeleteMileageLogApiMileageLogsMileageLogIdDeleteErrors];

export type DeleteMileageLogApiMileageLogsMileageLogIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteMileageLogApiMileageLogsMileageLogIdDeleteResponse = DeleteMileageLogApiMileageLogsMileageLogIdDeleteResponses[keyof DeleteMileageLogApiMileageLogsMileageLogIdDeleteResponses];

export type ListByCarApiServiceItemsGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Car Id
         */
        car_id: string;
    };
    url: '/api/service-items';
};

export type ListByCarApiServiceItemsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListByCarApiServiceItemsGetError = ListByCarApiServiceItemsGetErrors[keyof ListByCarApiServiceItemsGetErrors];

export type ListByCarApiServiceItemsGetResponses = {
    /**
     * Response List By Car Api Service Items Get
     *
     * Successful Response
     */
    200: Array<ServiceItemSummary>;
};

export type ListByCarApiServiceItemsGetResponse = ListByCarApiServiceItemsGetResponses[keyof ListByCarApiServiceItemsGetResponses];

export type AddServiceItemApiServiceItemsPostData = {
    body: ServiceItemCreate;
    path?: never;
    query?: never;
    url: '/api/service-items';
};

export type AddServiceItemApiServiceItemsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddServiceItemApiServiceItemsPostError = AddServiceItemApiServiceItemsPostErrors[keyof AddServiceItemApiServiceItemsPostErrors];

export type AddServiceItemApiServiceItemsPostResponses = {
    /**
     * Successful Response
     */
    201: ServiceItemRead;
};

export type AddServiceItemApiServiceItemsPostResponse = AddServiceItemApiServiceItemsPostResponses[keyof AddServiceItemApiServiceItemsPostResponses];

export type DeleteServiceItemApiServiceItemsServiceItemIdDeleteData = {
    body?: never;
    path: {
        /**
         * Service Item Id
         */
        service_item_id: string;
    };
    query?: never;
    url: '/api/service-items/{service_item_id}';
};

export type DeleteServiceItemApiServiceItemsServiceItemIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteServiceItemApiServiceItemsServiceItemIdDeleteError = DeleteServiceItemApiServiceItemsServiceItemIdDeleteErrors[keyof DeleteServiceItemApiServiceItemsServiceItemIdDeleteErrors];

export type DeleteServiceItemApiServiceItemsServiceItemIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteServiceItemApiServiceItemsServiceItemIdDeleteResponse = DeleteServiceItemApiServiceItemsServiceItemIdDeleteResponses[keyof DeleteServiceItemApiServiceItemsServiceItemIdDeleteResponses];

export type GetServiceItemApiServiceItemsServiceItemIdGetData = {
    body?: never;
    path: {
        /**
         * Service Item Id
         */
        service_item_id: string;
    };
    query?: never;
    url: '/api/service-items/{service_item_id}';
};

export type GetServiceItemApiServiceItemsServiceItemIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetServiceItemApiServiceItemsServiceItemIdGetError = GetServiceItemApiServiceItemsServiceItemIdGetErrors[keyof GetServiceItemApiServiceItemsServiceItemIdGetErrors];

export type GetServiceItemApiServiceItemsServiceItemIdGetResponses = {
    /**
     * Successful Response
     */
    200: ServiceItemRead;
};

export type GetServiceItemApiServiceItemsServiceItemIdGetResponse = GetServiceItemApiServiceItemsServiceItemIdGetResponses[keyof GetServiceItemApiServiceItemsServiceItemIdGetResponses];

export type UpdateServiceItemApiServiceItemsServiceItemIdPatchData = {
    body: ServiceItemUpdate;
    path: {
        /**
         * Service Item Id
         */
        service_item_id: string;
    };
    query?: never;
    url: '/api/service-items/{service_item_id}';
};

export type UpdateServiceItemApiServiceItemsServiceItemIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateServiceItemApiServiceItemsServiceItemIdPatchError = UpdateServiceItemApiServiceItemsServiceItemIdPatchErrors[keyof UpdateServiceItemApiServiceItemsServiceItemIdPatchErrors];

export type UpdateServiceItemApiServiceItemsServiceItemIdPatchResponses = {
    /**
     * Successful Response
     */
    200: ServiceItemRead;
};

export type UpdateServiceItemApiServiceItemsServiceItemIdPatchResponse = UpdateServiceItemApiServiceItemsServiceItemIdPatchResponses[keyof UpdateServiceItemApiServiceItemsServiceItemIdPatchResponses];

export type MarkServicedApiServiceItemsServiceItemIdMarkServicedPostData = {
    body: ServiceItemMarkServiced;
    path: {
        /**
         * Service Item Id
         */
        service_item_id: string;
    };
    query?: never;
    url: '/api/service-items/{service_item_id}/mark-serviced';
};

export type MarkServicedApiServiceItemsServiceItemIdMarkServicedPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MarkServicedApiServiceItemsServiceItemIdMarkServicedPostError = MarkServicedApiServiceItemsServiceItemIdMarkServicedPostErrors[keyof MarkServicedApiServiceItemsServiceItemIdMarkServicedPostErrors];

export type MarkServicedApiServiceItemsServiceItemIdMarkServicedPostResponses = {
    /**
     * Successful Response
     */
    200: ServiceItemRead;
};

export type MarkServicedApiServiceItemsServiceItemIdMarkServicedPostResponse = MarkServicedApiServiceItemsServiceItemIdMarkServicedPostResponses[keyof MarkServicedApiServiceItemsServiceItemIdMarkServicedPostResponses];

export type ListRemindersApiRemindersGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Car Id
         */
        car_id?: string | null;
        /**
         * Service Item Id
         */
        service_item_id?: string | null;
    };
    url: '/api/reminders';
};

export type ListRemindersApiRemindersGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListRemindersApiRemindersGetError = ListRemindersApiRemindersGetErrors[keyof ListRemindersApiRemindersGetErrors];

export type ListRemindersApiRemindersGetResponses = {
    /**
     * Response List Reminders Api Reminders Get
     *
     * Successful Response
     */
    200: Array<ReminderRead>;
};

export type ListRemindersApiRemindersGetResponse = ListRemindersApiRemindersGetResponses[keyof ListRemindersApiRemindersGetResponses];

export type AddReminderApiRemindersPostData = {
    body: ReminderCreate;
    path?: never;
    query?: never;
    url: '/api/reminders';
};

export type AddReminderApiRemindersPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddReminderApiRemindersPostError = AddReminderApiRemindersPostErrors[keyof AddReminderApiRemindersPostErrors];

export type AddReminderApiRemindersPostResponses = {
    /**
     * Successful Response
     */
    201: ReminderRead;
};

export type AddReminderApiRemindersPostResponse = AddReminderApiRemindersPostResponses[keyof AddReminderApiRemindersPostResponses];

export type DeleteReminderApiRemindersReminderIdDeleteData = {
    body?: never;
    path: {
        /**
         * Reminder Id
         */
        reminder_id: string;
    };
    query?: never;
    url: '/api/reminders/{reminder_id}';
};

export type DeleteReminderApiRemindersReminderIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteReminderApiRemindersReminderIdDeleteError = DeleteReminderApiRemindersReminderIdDeleteErrors[keyof DeleteReminderApiRemindersReminderIdDeleteErrors];

export type DeleteReminderApiRemindersReminderIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteReminderApiRemindersReminderIdDeleteResponse = DeleteReminderApiRemindersReminderIdDeleteResponses[keyof DeleteReminderApiRemindersReminderIdDeleteResponses];

export type GetReminderApiRemindersReminderIdGetData = {
    body?: never;
    path: {
        /**
         * Reminder Id
         */
        reminder_id: string;
    };
    query?: never;
    url: '/api/reminders/{reminder_id}';
};

export type GetReminderApiRemindersReminderIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetReminderApiRemindersReminderIdGetError = GetReminderApiRemindersReminderIdGetErrors[keyof GetReminderApiRemindersReminderIdGetErrors];

export type GetReminderApiRemindersReminderIdGetResponses = {
    /**
     * Successful Response
     */
    200: ReminderRead;
};

export type GetReminderApiRemindersReminderIdGetResponse = GetReminderApiRemindersReminderIdGetResponses[keyof GetReminderApiRemindersReminderIdGetResponses];

export type UpdateReminderApiRemindersReminderIdPatchData = {
    body: ReminderUpdate;
    path: {
        /**
         * Reminder Id
         */
        reminder_id: string;
    };
    query?: never;
    url: '/api/reminders/{reminder_id}';
};

export type UpdateReminderApiRemindersReminderIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateReminderApiRemindersReminderIdPatchError = UpdateReminderApiRemindersReminderIdPatchErrors[keyof UpdateReminderApiRemindersReminderIdPatchErrors];

export type UpdateReminderApiRemindersReminderIdPatchResponses = {
    /**
     * Successful Response
     */
    200: ReminderRead;
};

export type UpdateReminderApiRemindersReminderIdPatchResponse = UpdateReminderApiRemindersReminderIdPatchResponses[keyof UpdateReminderApiRemindersReminderIdPatchResponses];

export type TelegramAuthApiTelegramAuthPostData = {
    body: TelegramAuthRequest;
    path?: never;
    query?: never;
    url: '/api/telegram/auth';
};

export type TelegramAuthApiTelegramAuthPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TelegramAuthApiTelegramAuthPostError = TelegramAuthApiTelegramAuthPostErrors[keyof TelegramAuthApiTelegramAuthPostErrors];

export type TelegramAuthApiTelegramAuthPostResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type TelegramAuthApiTelegramAuthPostResponse = TelegramAuthApiTelegramAuthPostResponses[keyof TelegramAuthApiTelegramAuthPostResponses];

export type GetBotWebhookApiTelegramWebhookGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/telegram/webhook';
};

export type GetBotWebhookApiTelegramWebhookGetResponses = {
    /**
     * Response Get Bot Webhook Api Telegram Webhook Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetBotWebhookApiTelegramWebhookGetResponse = GetBotWebhookApiTelegramWebhookGetResponses[keyof GetBotWebhookApiTelegramWebhookGetResponses];

export type BotWebhookApiTelegramWebhookPostData = {
    body?: never;
    headers?: {
        /**
         * X-Telegram-Bot-Api-Secret-Token
         */
        'X-Telegram-Bot-Api-Secret-Token'?: string;
    };
    path?: never;
    query?: never;
    url: '/api/telegram/webhook';
};

export type BotWebhookApiTelegramWebhookPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BotWebhookApiTelegramWebhookPostError = BotWebhookApiTelegramWebhookPostErrors[keyof BotWebhookApiTelegramWebhookPostErrors];

export type BotWebhookApiTelegramWebhookPostResponses = {
    /**
     * Response Bot Webhook Api Telegram Webhook Post
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type BotWebhookApiTelegramWebhookPostResponse = BotWebhookApiTelegramWebhookPostResponses[keyof BotWebhookApiTelegramWebhookPostResponses];

export type GetLinkTokenApiTelegramLinkTokenPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/telegram/link-token';
};

export type GetLinkTokenApiTelegramLinkTokenPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetLinkTokenApiTelegramLinkTokenPostError = GetLinkTokenApiTelegramLinkTokenPostErrors[keyof GetLinkTokenApiTelegramLinkTokenPostErrors];

export type GetLinkTokenApiTelegramLinkTokenPostResponses = {
    /**
     * Successful Response
     */
    200: TelegramLinkTokenResponse;
};

export type GetLinkTokenApiTelegramLinkTokenPostResponse = GetLinkTokenApiTelegramLinkTokenPostResponses[keyof GetLinkTokenApiTelegramLinkTokenPostResponses];

export type UnlinkTelegramApiTelegramLinkDeleteData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/telegram/link';
};

export type UnlinkTelegramApiTelegramLinkDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UnlinkTelegramApiTelegramLinkDeleteError = UnlinkTelegramApiTelegramLinkDeleteErrors[keyof UnlinkTelegramApiTelegramLinkDeleteErrors];

export type UnlinkTelegramApiTelegramLinkDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type UnlinkTelegramApiTelegramLinkDeleteResponse = UnlinkTelegramApiTelegramLinkDeleteResponses[keyof UnlinkTelegramApiTelegramLinkDeleteResponses];
