// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://127.0.0.1:4267' | (string & {});
};

/**
 * Body_login_api_auth_login_post
 */
export type BodyLoginApiAuthLoginPost = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * CarCreate
 */
export type CarCreate = {
    /**
     * Brand
     */
    brand: string;
    /**
     * Model
     */
    model: string;
    /**
     * Year
     */
    year: number;
    /**
     * Initial Odometer Km
     */
    initial_odometer_km: number;
};

/**
 * CarRead
 */
export type CarRead = {
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Brand
     */
    brand: string;
    /**
     * Model
     */
    model: string;
    /**
     * Year
     */
    year: number;
    /**
     * Initial Odometer Km
     */
    initial_odometer_km: number;
    /**
     * Current Odometer Km
     */
    current_odometer_km: number;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * CarUpdate
 */
export type CarUpdate = {
    /**
     * Brand
     */
    brand?: string | null;
    /**
     * Model
     */
    model?: string | null;
    /**
     * Year
     */
    year?: number | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * MileageLogCreate
 */
export type MileageLogCreate = {
    /**
     * Car Id
     */
    car_id: string;
    /**
     * Odometer Km
     */
    odometer_km: number;
};

/**
 * MileageLogRead
 */
export type MileageLogRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Car Id
     */
    car_id: string;
    /**
     * Odometer Km
     */
    odometer_km: number;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * ReminderCreate
 */
export type ReminderCreate = {
    /**
     * Service Item Id
     */
    service_item_id: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Interval Km
     */
    interval_km?: number | null;
    /**
     * Interval Days
     */
    interval_days?: number | null;
    /**
     * Notify Before Km
     */
    notify_before_km?: number | null;
    /**
     * Notify Before Days
     */
    notify_before_days?: number | null;
    /**
     * Note
     */
    note?: string | null;
};

/**
 * ReminderRead
 */
export type ReminderRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Service Item Id
     */
    service_item_id: string;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Interval Km
     */
    interval_km: number | null;
    /**
     * Interval Days
     */
    interval_days: number | null;
    /**
     * Notify Before Km
     */
    notify_before_km: number | null;
    /**
     * Notify Before Days
     */
    notify_before_days: number | null;
    /**
     * Note
     */
    note: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * ReminderUpdate
 */
export type ReminderUpdate = {
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Interval Km
     */
    interval_km?: number | null;
    /**
     * Interval Days
     */
    interval_days?: number | null;
    /**
     * Notify Before Km
     */
    notify_before_km?: number | null;
    /**
     * Notify Before Days
     */
    notify_before_days?: number | null;
    /**
     * Note
     */
    note?: string | null;
};

/**
 * ServiceItemCreate
 */
export type ServiceItemCreate = {
    /**
     * Car Id
     */
    car_id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Last Service At
     */
    last_service_at: string;
    /**
     * Last Service Odometer Km
     */
    last_service_odometer_km: number;
};

/**
 * ServiceItemMarkServiced
 */
export type ServiceItemMarkServiced = {
    /**
     * Serviced At
     */
    serviced_at: string;
    /**
     * Odometer Km
     */
    odometer_km: number;
};

/**
 * ServiceItemRead
 */
export type ServiceItemRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Car Id
     */
    car_id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Last Service At
     */
    last_service_at: string;
    /**
     * Last Service Odometer Km
     */
    last_service_odometer_km: number;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * ServiceItemUpdate
 */
export type ServiceItemUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Last Service At
     */
    last_service_at?: string | null;
    /**
     * Last Service Odometer Km
     */
    last_service_odometer_km?: number | null;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Username
     */
    username: string;
    /**
     * Name
     */
    name: string;
    /**
     * Password
     */
    password: string;
};

/**
 * UserRead
 */
export type UserRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Username
     */
    username: string;
    /**
     * Name
     */
    name: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Username
     */
    username?: string | null;
    /**
     * Name
     */
    name?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type LoginApiAuthLoginPostData = {
    body: BodyLoginApiAuthLoginPost;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type LoginApiAuthLoginPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginApiAuthLoginPostError = LoginApiAuthLoginPostErrors[keyof LoginApiAuthLoginPostErrors];

export type LoginApiAuthLoginPostResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type LoginApiAuthLoginPostResponse = LoginApiAuthLoginPostResponses[keyof LoginApiAuthLoginPostResponses];

export type LogoutApiAuthLogoutPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/logout';
};

export type LogoutApiAuthLogoutPostResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type LogoutApiAuthLogoutPostResponse = LogoutApiAuthLogoutPostResponses[keyof LogoutApiAuthLogoutPostResponses];

export type GetMeApiAuthMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/me';
};

export type GetMeApiAuthMeGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMeApiAuthMeGetError = GetMeApiAuthMeGetErrors[keyof GetMeApiAuthMeGetErrors];

export type GetMeApiAuthMeGetResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type GetMeApiAuthMeGetResponse = GetMeApiAuthMeGetResponses[keyof GetMeApiAuthMeGetResponses];

export type RegisterUserApiUsersPostData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/users';
};

export type RegisterUserApiUsersPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterUserApiUsersPostError = RegisterUserApiUsersPostErrors[keyof RegisterUserApiUsersPostErrors];

export type RegisterUserApiUsersPostResponses = {
    /**
     * Successful Response
     */
    201: UserRead;
};

export type RegisterUserApiUsersPostResponse = RegisterUserApiUsersPostResponses[keyof RegisterUserApiUsersPostResponses];

export type GetUserByUsernameApiUsersUusernameGetData = {
    body?: never;
    path: {
        /**
         * Username
         */
        username: string;
    };
    query?: never;
    url: '/api/users/u/{username}';
};

export type GetUserByUsernameApiUsersUusernameGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUserByUsernameApiUsersUusernameGetError = GetUserByUsernameApiUsersUusernameGetErrors[keyof GetUserByUsernameApiUsersUusernameGetErrors];

export type GetUserByUsernameApiUsersUusernameGetResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type GetUserByUsernameApiUsersUusernameGetResponse = GetUserByUsernameApiUsersUusernameGetResponses[keyof GetUserByUsernameApiUsersUusernameGetResponses];

export type DeleteUserApiUsersUserIdDeleteData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/users/{user_id}';
};

export type DeleteUserApiUsersUserIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteUserApiUsersUserIdDeleteError = DeleteUserApiUsersUserIdDeleteErrors[keyof DeleteUserApiUsersUserIdDeleteErrors];

export type DeleteUserApiUsersUserIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteUserApiUsersUserIdDeleteResponse = DeleteUserApiUsersUserIdDeleteResponses[keyof DeleteUserApiUsersUserIdDeleteResponses];

export type GetUserApiUsersUserIdGetData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/users/{user_id}';
};

export type GetUserApiUsersUserIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUserApiUsersUserIdGetError = GetUserApiUsersUserIdGetErrors[keyof GetUserApiUsersUserIdGetErrors];

export type GetUserApiUsersUserIdGetResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type GetUserApiUsersUserIdGetResponse = GetUserApiUsersUserIdGetResponses[keyof GetUserApiUsersUserIdGetResponses];

export type UpdateUserApiUsersUserIdPatchData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/users/{user_id}';
};

export type UpdateUserApiUsersUserIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUserApiUsersUserIdPatchError = UpdateUserApiUsersUserIdPatchErrors[keyof UpdateUserApiUsersUserIdPatchErrors];

export type UpdateUserApiUsersUserIdPatchResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type UpdateUserApiUsersUserIdPatchResponse = UpdateUserApiUsersUserIdPatchResponses[keyof UpdateUserApiUsersUserIdPatchResponses];

export type ListUserCarsApiCarsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/cars';
};

export type ListUserCarsApiCarsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListUserCarsApiCarsGetError = ListUserCarsApiCarsGetErrors[keyof ListUserCarsApiCarsGetErrors];

export type ListUserCarsApiCarsGetResponses = {
    /**
     * Response List User Cars Api Cars Get
     *
     * Successful Response
     */
    200: Array<CarRead>;
};

export type ListUserCarsApiCarsGetResponse = ListUserCarsApiCarsGetResponses[keyof ListUserCarsApiCarsGetResponses];

export type AddCarApiCarsPostData = {
    body: CarCreate;
    path?: never;
    query?: never;
    url: '/api/cars';
};

export type AddCarApiCarsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddCarApiCarsPostError = AddCarApiCarsPostErrors[keyof AddCarApiCarsPostErrors];

export type AddCarApiCarsPostResponses = {
    /**
     * Successful Response
     */
    201: CarRead;
};

export type AddCarApiCarsPostResponse = AddCarApiCarsPostResponses[keyof AddCarApiCarsPostResponses];

export type DeleteCarApiCarsCarIdDeleteData = {
    body?: never;
    path: {
        /**
         * Car Id
         */
        car_id: string;
    };
    query?: never;
    url: '/api/cars/{car_id}';
};

export type DeleteCarApiCarsCarIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteCarApiCarsCarIdDeleteError = DeleteCarApiCarsCarIdDeleteErrors[keyof DeleteCarApiCarsCarIdDeleteErrors];

export type DeleteCarApiCarsCarIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteCarApiCarsCarIdDeleteResponse = DeleteCarApiCarsCarIdDeleteResponses[keyof DeleteCarApiCarsCarIdDeleteResponses];

export type GetCarApiCarsCarIdGetData = {
    body?: never;
    path: {
        /**
         * Car Id
         */
        car_id: string;
    };
    query?: never;
    url: '/api/cars/{car_id}';
};

export type GetCarApiCarsCarIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCarApiCarsCarIdGetError = GetCarApiCarsCarIdGetErrors[keyof GetCarApiCarsCarIdGetErrors];

export type GetCarApiCarsCarIdGetResponses = {
    /**
     * Successful Response
     */
    200: CarRead;
};

export type GetCarApiCarsCarIdGetResponse = GetCarApiCarsCarIdGetResponses[keyof GetCarApiCarsCarIdGetResponses];

export type UpdateCarApiCarsCarIdPatchData = {
    body: CarUpdate;
    path: {
        /**
         * Car Id
         */
        car_id: string;
    };
    query?: never;
    url: '/api/cars/{car_id}';
};

export type UpdateCarApiCarsCarIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateCarApiCarsCarIdPatchError = UpdateCarApiCarsCarIdPatchErrors[keyof UpdateCarApiCarsCarIdPatchErrors];

export type UpdateCarApiCarsCarIdPatchResponses = {
    /**
     * Successful Response
     */
    200: CarRead;
};

export type UpdateCarApiCarsCarIdPatchResponse = UpdateCarApiCarsCarIdPatchResponses[keyof UpdateCarApiCarsCarIdPatchResponses];

export type AddMileageLogApiMileageLogsPostData = {
    body: MileageLogCreate;
    path?: never;
    query?: never;
    url: '/api/mileage-logs';
};

export type AddMileageLogApiMileageLogsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddMileageLogApiMileageLogsPostError = AddMileageLogApiMileageLogsPostErrors[keyof AddMileageLogApiMileageLogsPostErrors];

export type AddMileageLogApiMileageLogsPostResponses = {
    /**
     * Successful Response
     */
    201: MileageLogRead;
};

export type AddMileageLogApiMileageLogsPostResponse = AddMileageLogApiMileageLogsPostResponses[keyof AddMileageLogApiMileageLogsPostResponses];

export type ListByCarApiMileageLogsCarCarIdGetData = {
    body?: never;
    path: {
        /**
         * Car Id
         */
        car_id: string;
    };
    query?: never;
    url: '/api/mileage-logs/car/{car_id}';
};

export type ListByCarApiMileageLogsCarCarIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListByCarApiMileageLogsCarCarIdGetError = ListByCarApiMileageLogsCarCarIdGetErrors[keyof ListByCarApiMileageLogsCarCarIdGetErrors];

export type ListByCarApiMileageLogsCarCarIdGetResponses = {
    /**
     * Response List By Car Api Mileage Logs Car  Car Id  Get
     *
     * Successful Response
     */
    200: Array<MileageLogRead>;
};

export type ListByCarApiMileageLogsCarCarIdGetResponse = ListByCarApiMileageLogsCarCarIdGetResponses[keyof ListByCarApiMileageLogsCarCarIdGetResponses];

export type DeleteMileageLogApiMileageLogsMileageLogIdDeleteData = {
    body?: never;
    path: {
        /**
         * Mileage Log Id
         */
        mileage_log_id: string;
    };
    query?: never;
    url: '/api/mileage-logs/{mileage_log_id}';
};

export type DeleteMileageLogApiMileageLogsMileageLogIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteMileageLogApiMileageLogsMileageLogIdDeleteError = DeleteMileageLogApiMileageLogsMileageLogIdDeleteErrors[keyof DeleteMileageLogApiMileageLogsMileageLogIdDeleteErrors];

export type DeleteMileageLogApiMileageLogsMileageLogIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteMileageLogApiMileageLogsMileageLogIdDeleteResponse = DeleteMileageLogApiMileageLogsMileageLogIdDeleteResponses[keyof DeleteMileageLogApiMileageLogsMileageLogIdDeleteResponses];

export type AddServiceItemApiServiceItemsPostData = {
    body: ServiceItemCreate;
    path?: never;
    query?: never;
    url: '/api/service-items';
};

export type AddServiceItemApiServiceItemsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddServiceItemApiServiceItemsPostError = AddServiceItemApiServiceItemsPostErrors[keyof AddServiceItemApiServiceItemsPostErrors];

export type AddServiceItemApiServiceItemsPostResponses = {
    /**
     * Successful Response
     */
    201: ServiceItemRead;
};

export type AddServiceItemApiServiceItemsPostResponse = AddServiceItemApiServiceItemsPostResponses[keyof AddServiceItemApiServiceItemsPostResponses];

export type ListByCarApiServiceItemsCarCarIdGetData = {
    body?: never;
    path: {
        /**
         * Car Id
         */
        car_id: string;
    };
    query?: never;
    url: '/api/service-items/car/{car_id}';
};

export type ListByCarApiServiceItemsCarCarIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListByCarApiServiceItemsCarCarIdGetError = ListByCarApiServiceItemsCarCarIdGetErrors[keyof ListByCarApiServiceItemsCarCarIdGetErrors];

export type ListByCarApiServiceItemsCarCarIdGetResponses = {
    /**
     * Response List By Car Api Service Items Car  Car Id  Get
     *
     * Successful Response
     */
    200: Array<ServiceItemRead>;
};

export type ListByCarApiServiceItemsCarCarIdGetResponse = ListByCarApiServiceItemsCarCarIdGetResponses[keyof ListByCarApiServiceItemsCarCarIdGetResponses];

export type DeleteServiceItemApiServiceItemsServiceItemIdDeleteData = {
    body?: never;
    path: {
        /**
         * Service Item Id
         */
        service_item_id: string;
    };
    query?: never;
    url: '/api/service-items/{service_item_id}';
};

export type DeleteServiceItemApiServiceItemsServiceItemIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteServiceItemApiServiceItemsServiceItemIdDeleteError = DeleteServiceItemApiServiceItemsServiceItemIdDeleteErrors[keyof DeleteServiceItemApiServiceItemsServiceItemIdDeleteErrors];

export type DeleteServiceItemApiServiceItemsServiceItemIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteServiceItemApiServiceItemsServiceItemIdDeleteResponse = DeleteServiceItemApiServiceItemsServiceItemIdDeleteResponses[keyof DeleteServiceItemApiServiceItemsServiceItemIdDeleteResponses];

export type GetServiceItemApiServiceItemsServiceItemIdGetData = {
    body?: never;
    path: {
        /**
         * Service Item Id
         */
        service_item_id: string;
    };
    query?: never;
    url: '/api/service-items/{service_item_id}';
};

export type GetServiceItemApiServiceItemsServiceItemIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetServiceItemApiServiceItemsServiceItemIdGetError = GetServiceItemApiServiceItemsServiceItemIdGetErrors[keyof GetServiceItemApiServiceItemsServiceItemIdGetErrors];

export type GetServiceItemApiServiceItemsServiceItemIdGetResponses = {
    /**
     * Successful Response
     */
    200: ServiceItemRead;
};

export type GetServiceItemApiServiceItemsServiceItemIdGetResponse = GetServiceItemApiServiceItemsServiceItemIdGetResponses[keyof GetServiceItemApiServiceItemsServiceItemIdGetResponses];

export type UpdateServiceItemApiServiceItemsServiceItemIdPatchData = {
    body: ServiceItemUpdate;
    path: {
        /**
         * Service Item Id
         */
        service_item_id: string;
    };
    query?: never;
    url: '/api/service-items/{service_item_id}';
};

export type UpdateServiceItemApiServiceItemsServiceItemIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateServiceItemApiServiceItemsServiceItemIdPatchError = UpdateServiceItemApiServiceItemsServiceItemIdPatchErrors[keyof UpdateServiceItemApiServiceItemsServiceItemIdPatchErrors];

export type UpdateServiceItemApiServiceItemsServiceItemIdPatchResponses = {
    /**
     * Successful Response
     */
    200: ServiceItemRead;
};

export type UpdateServiceItemApiServiceItemsServiceItemIdPatchResponse = UpdateServiceItemApiServiceItemsServiceItemIdPatchResponses[keyof UpdateServiceItemApiServiceItemsServiceItemIdPatchResponses];

export type MarkServicedApiServiceItemsServiceItemIdMarkServicedPostData = {
    body: ServiceItemMarkServiced;
    path: {
        /**
         * Service Item Id
         */
        service_item_id: string;
    };
    query?: never;
    url: '/api/service-items/{service_item_id}/mark-serviced';
};

export type MarkServicedApiServiceItemsServiceItemIdMarkServicedPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MarkServicedApiServiceItemsServiceItemIdMarkServicedPostError = MarkServicedApiServiceItemsServiceItemIdMarkServicedPostErrors[keyof MarkServicedApiServiceItemsServiceItemIdMarkServicedPostErrors];

export type MarkServicedApiServiceItemsServiceItemIdMarkServicedPostResponses = {
    /**
     * Successful Response
     */
    200: ServiceItemRead;
};

export type MarkServicedApiServiceItemsServiceItemIdMarkServicedPostResponse = MarkServicedApiServiceItemsServiceItemIdMarkServicedPostResponses[keyof MarkServicedApiServiceItemsServiceItemIdMarkServicedPostResponses];

export type AddReminderApiRemindersPostData = {
    body: ReminderCreate;
    path?: never;
    query?: never;
    url: '/api/reminders';
};

export type AddReminderApiRemindersPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddReminderApiRemindersPostError = AddReminderApiRemindersPostErrors[keyof AddReminderApiRemindersPostErrors];

export type AddReminderApiRemindersPostResponses = {
    /**
     * Successful Response
     */
    201: ReminderRead;
};

export type AddReminderApiRemindersPostResponse = AddReminderApiRemindersPostResponses[keyof AddReminderApiRemindersPostResponses];

export type ListByServiceItemApiRemindersServiceItemServiceItemIdGetData = {
    body?: never;
    path: {
        /**
         * Service Item Id
         */
        service_item_id: string;
    };
    query?: never;
    url: '/api/reminders/service-item/{service_item_id}';
};

export type ListByServiceItemApiRemindersServiceItemServiceItemIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListByServiceItemApiRemindersServiceItemServiceItemIdGetError = ListByServiceItemApiRemindersServiceItemServiceItemIdGetErrors[keyof ListByServiceItemApiRemindersServiceItemServiceItemIdGetErrors];

export type ListByServiceItemApiRemindersServiceItemServiceItemIdGetResponses = {
    /**
     * Response List By Service Item Api Reminders Service Item  Service Item Id  Get
     *
     * Successful Response
     */
    200: Array<ReminderRead>;
};

export type ListByServiceItemApiRemindersServiceItemServiceItemIdGetResponse = ListByServiceItemApiRemindersServiceItemServiceItemIdGetResponses[keyof ListByServiceItemApiRemindersServiceItemServiceItemIdGetResponses];

export type ListActiveByServiceItemApiRemindersServiceItemServiceItemIdActiveGetData = {
    body?: never;
    path: {
        /**
         * Service Item Id
         */
        service_item_id: string;
    };
    query?: never;
    url: '/api/reminders/service-item/{service_item_id}/active';
};

export type ListActiveByServiceItemApiRemindersServiceItemServiceItemIdActiveGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListActiveByServiceItemApiRemindersServiceItemServiceItemIdActiveGetError = ListActiveByServiceItemApiRemindersServiceItemServiceItemIdActiveGetErrors[keyof ListActiveByServiceItemApiRemindersServiceItemServiceItemIdActiveGetErrors];

export type ListActiveByServiceItemApiRemindersServiceItemServiceItemIdActiveGetResponses = {
    /**
     * Response List Active By Service Item Api Reminders Service Item  Service Item Id  Active Get
     *
     * Successful Response
     */
    200: Array<ReminderRead>;
};

export type ListActiveByServiceItemApiRemindersServiceItemServiceItemIdActiveGetResponse = ListActiveByServiceItemApiRemindersServiceItemServiceItemIdActiveGetResponses[keyof ListActiveByServiceItemApiRemindersServiceItemServiceItemIdActiveGetResponses];

export type DeleteReminderApiRemindersReminderIdDeleteData = {
    body?: never;
    path: {
        /**
         * Reminder Id
         */
        reminder_id: string;
    };
    query?: never;
    url: '/api/reminders/{reminder_id}';
};

export type DeleteReminderApiRemindersReminderIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteReminderApiRemindersReminderIdDeleteError = DeleteReminderApiRemindersReminderIdDeleteErrors[keyof DeleteReminderApiRemindersReminderIdDeleteErrors];

export type DeleteReminderApiRemindersReminderIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteReminderApiRemindersReminderIdDeleteResponse = DeleteReminderApiRemindersReminderIdDeleteResponses[keyof DeleteReminderApiRemindersReminderIdDeleteResponses];

export type GetReminderApiRemindersReminderIdGetData = {
    body?: never;
    path: {
        /**
         * Reminder Id
         */
        reminder_id: string;
    };
    query?: never;
    url: '/api/reminders/{reminder_id}';
};

export type GetReminderApiRemindersReminderIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetReminderApiRemindersReminderIdGetError = GetReminderApiRemindersReminderIdGetErrors[keyof GetReminderApiRemindersReminderIdGetErrors];

export type GetReminderApiRemindersReminderIdGetResponses = {
    /**
     * Successful Response
     */
    200: ReminderRead;
};

export type GetReminderApiRemindersReminderIdGetResponse = GetReminderApiRemindersReminderIdGetResponses[keyof GetReminderApiRemindersReminderIdGetResponses];

export type UpdateReminderApiRemindersReminderIdPatchData = {
    body: ReminderUpdate;
    path: {
        /**
         * Reminder Id
         */
        reminder_id: string;
    };
    query?: never;
    url: '/api/reminders/{reminder_id}';
};

export type UpdateReminderApiRemindersReminderIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateReminderApiRemindersReminderIdPatchError = UpdateReminderApiRemindersReminderIdPatchErrors[keyof UpdateReminderApiRemindersReminderIdPatchErrors];

export type UpdateReminderApiRemindersReminderIdPatchResponses = {
    /**
     * Successful Response
     */
    200: ReminderRead;
};

export type UpdateReminderApiRemindersReminderIdPatchResponse = UpdateReminderApiRemindersReminderIdPatchResponses[keyof UpdateReminderApiRemindersReminderIdPatchResponses];
