"""add last_notified_at to reminders

Revision ID: a65541b7f34c
Revises: a378900561c0
Create Date: 2026-08-09 00:57:07.205794

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a65541b7f34c"
down_revision: str | Sequence[str] | None = "a378900561c0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("reminders", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "last_notified_at",
                sa.DateTime(timezone=True),
                nullable=True,
                comment="Timestamp of the last sent notification",
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("reminders", schema=None) as batch_op:
        batch_op.drop_column("last_notified_at")

    # ### end Alembic commands ###
