"""add_user_settings_and_email

Revision ID: a378900561c0
Revises: 9a80387ade5a
Create Date: 2026-08-07 14:39:41.249643

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a378900561c0"
down_revision: str | Sequence[str] | None = "9a80387ade5a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_settings",
        sa.Column("user_id", sa.Uuid(), nullable=False, comment="ID of the user"),
        sa.Column(
            "service_reminder_time",
            sa.Time(),
            server_default=sa.text("'12:00:00'"),
            nullable=False,
            comment="Preferred time of day for service reminders",
        ),
        sa.Column(
            "mileage_reminder_time",
            sa.Time(),
            server_default=sa.text("'19:00:00'"),
            nullable=False,
            comment="Preferred time of day for mileage prompts",
        ),
        sa.Column(
            "mileage_prompt_interval_days",
            sa.Integer(),
            server_default=sa.text("(14)"),
            nullable=True,
            comment="Interval in days to prompt user for mileage update",
        ),
        sa.Column(
            "timezone",
            sa.String(length=64),
            server_default=sa.text("'Europe/Moscow'"),
            nullable=False,
            comment="User timezone name",
        ),
        sa.Column(
            "notify_via_telegram",
            sa.Boolean(),
            server_default=sa.text("(TRUE)"),
            nullable=False,
            comment="Enable notifications via Telegram",
        ),
        sa.Column(
            "notify_via_email",
            sa.Boolean(),
            server_default=sa.text("(FALSE)"),
            nullable=False,
            comment="Enable notifications via Email",
        ),
        sa.Column(
            "language",
            sa.String(length=10),
            server_default=sa.text("'ru'"),
            nullable=False,
            comment="User preferred language (ru/en)",
        ),
        sa.Column("id", sa.Uuid(), nullable=False, comment="Unique identifier"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="Date and time of creation",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="Date and time of last update",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_settings_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_settings")),
        sa.UniqueConstraint("user_id", name=op.f("uq_user_settings_user_id")),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("email", sa.String(), nullable=True, comment="User email address")
        )
        batch_op.create_unique_constraint(batch_op.f("uq_users_email"), ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("uq_users_email"), type_="unique")
        batch_op.drop_column("email")

    op.drop_table("user_settings")
    # ### end Alembic commands ###
